sudo: false

language: ruby

services: mongodb

env:
  - MONGOID_VERSION=3
  - MONGOID_VERSION=4
  - MONGOID_VERSION=5.0.0
  - MONGOID_VERSION=5
  - MONGOID_VERSION=HEAD

rvm:
  - jruby-19mode
  - 1.9.3
  - 2.0.0
  - 2.2

before_install:
  - gem update bundler
